title: Mees Kaandorp
email: meeskaandorp@gmail.com
author: Tijmen Stor
description: >-
  Portfolio website of Mees Kaandorp
url: "http://meeskaandorp.nl" 
instagram_username: mees.kaandorp
linkedin_username: meeskaandorp

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
